"""Self-update — fetch the agent's own source from `origin` and re-sync deps.

Restricted by design:
  - Operates ONLY inside the project directory (parent of this file).
  - Talks to whichever `origin` remote is already configured locally.
    We never accept a URL from the LLM, so the LLM cannot redirect the
    update to a different repository.
  - Refuses to overwrite uncommitted local changes.
  - Uses `--ff-only` so a divergent history will fail loudly instead of
    silently merging.
  - The new code only takes effect after the user restarts the agent;
    Python keeps the old modules cached in this process.
"""

from __future__ import annotations

import asyncio
import os
import shutil
from pathlib import Path
from typing import Any


# The project root = the directory containing this file's parent
# (tools/) — i.e. the repo root. Resolved once at import time.
_PROJECT_DIR: Path = Path(__file__).resolve().parent.parent


def _clean_env() -> dict[str, str]:
    """Strip the runtime-library vars Decky Loader (a PyInstaller binary)
    injects into plugin backends.

    Decky unpacks its own bundled libssl/libcrypto to /tmp/_MEI*/ and points
    LD_LIBRARY_PATH at them. Subprocesses inherit those vars, so a system
    `git` loads Decky's stale libssl instead of the OS one — its libcurl
    HTTPS handshake then dies (e.g. `libssl.so.3: version 'OPENSSL_3.x.0'
    not found`), which surfaces as a `git fetch` failure, not a hang.
    Dropping these vars makes git use the system libraries again.
    """
    env = os.environ.copy()
    for key in ("LD_LIBRARY_PATH", "LD_PRELOAD", "PYTHONHOME",
                "PYTHONPATH", "_MEIPASS", "_MEIPASS2"):
        env.pop(key, None)
    # Point HOME at the desktop user's home: under Decky the backend runs as
    # root (HOME=/root), so git can't see the deck user's ~/.gitconfig — which
    # often holds the GitHub mirror/proxy needed on restricted networks. Without
    # it, root's git hits github.com directly and stalls until timeout, while
    # the same pull works instantly in the user's terminal.
    deck_home = os.environ.get("DECKY_USER_HOME")
    if deck_home:
        env["HOME"] = deck_home
    # Never block on a credential prompt when there's no tty.
    env["GIT_TERMINAL_PROMPT"] = "0"
    return env


async def _git(*args: str) -> tuple[int, str, str]:
    """Run a git command inside the project directory."""
    proc = await asyncio.create_subprocess_exec(
        # safe.directory=*: root operating on a deck-owned repo would otherwise
        # be refused with "dubious ownership".
        "git", "-c", "safe.directory=*", *args,
        cwd=str(_PROJECT_DIR),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env=_clean_env(),
    )
    out, err = await proc.communicate()
    return (
        proc.returncode or 0,
        out.decode(errors="ignore").strip(),
        err.decode(errors="ignore").strip(),
    )


def _preflight() -> dict[str, Any] | None:
    """Return an error dict if the environment isn't usable for updates."""
    if not shutil.which("git"):
        return {"ok": False, "error": "git is not installed"}
    if not (_PROJECT_DIR / ".git").exists():
        return {"ok": False,
                "error": "project is not a git checkout — cannot self-update"}
    return None


# ---------- read-only ----------

async def check_for_updates() -> dict[str, Any]:
    """Fetch from `origin` and report how far behind we are."""
    err = _preflight()
    if err:
        return err

    rc, _, stderr = await _git("fetch", "--quiet")
    if rc != 0:
        return {"ok": False, "error": f"git fetch failed: {stderr or '(no message)'}"}

    rc, local, _ = await _git("rev-parse", "HEAD")
    if rc != 0:
        return {"ok": False, "error": "could not read HEAD commit"}

    rc, remote, _ = await _git("rev-parse", "@{u}")
    if rc != 0:
        return {"ok": False,
                "error": "current branch has no upstream — set one with "
                         "`git branch --set-upstream-to=origin/main`"}

    if local == remote:
        return {"ok": True, "up_to_date": True, "commit": local[:7]}

    rc, log, _ = await _git("log", "--oneline", "HEAD..@{u}")
    new_commits = log.splitlines()[:20] if log else []

    # Only TRACKED file modifications block a pull. Untracked files
    # (e.g. uv.lock generated by `uv sync`) don't conflict — git pull
    # leaves them alone.
    rc, tracked, _ = await _git("status", "--porcelain", "--untracked-files=no")
    modified_tracked = tracked.splitlines() if tracked else []

    rc, all_status, _ = await _git("status", "--porcelain")
    untracked = [
        line[3:] for line in (all_status.splitlines() if all_status else [])
        if line.startswith("?? ")
    ]

    return {
        "ok": True,
        "up_to_date": False,
        "local": local[:7],
        "remote": remote[:7],
        "behind_by": len(new_commits),
        "new_commits": new_commits,
        # Tracked-file changes are blocking; untracked are informational.
        "modified_tracked_files": modified_tracked,
        "would_block_pull": bool(modified_tracked),
        "untracked_files": untracked,
    }


# ---------- destructive ----------

async def apply_update(confirm: bool = False) -> dict[str, Any]:
    """`git pull --ff-only` + `uv sync`. Two-step confirmation."""
    err = _preflight()
    if err:
        return err

    if not confirm:
        preview = await check_for_updates()
        if not preview.get("ok"):
            return preview
        if preview.get("up_to_date"):
            return {"ok": True, "dry_run": True, "up_to_date": True,
                    "message": f"Already up to date at {preview['commit']}."}
        return {
            "ok": True, "dry_run": True,
            "from": preview["local"], "to": preview["remote"],
            "behind_by": preview["behind_by"],
            "new_commits": preview["new_commits"],
            "would_block_pull": preview["would_block_pull"],
            "modified_tracked_files": preview["modified_tracked_files"],
            "untracked_files": preview["untracked_files"],
            "message": (
                "Ask the user to confirm, then call again with confirm=true. "
                "After updating, the agent must be restarted to load the new code."
            ),
        }

    # Refuse outright only if TRACKED files have uncommitted edits —
    # pulling those would fail or overwrite the user's work. Untracked
    # files (uv.lock, scratch notes, etc.) are left alone by git pull
    # and never block.
    rc, tracked, _ = await _git("status", "--porcelain", "--untracked-files=no")
    modified = tracked.splitlines() if tracked else []
    if modified:
        return {
            "ok": False, "refused": True,
            "reason": ("uncommitted local edits to tracked files — refusing "
                       "to pull to avoid losing work"),
            "files": modified,
            "hint": "Commit, stash, or discard those edits manually first.",
        }

    rc, pull_out, pull_err = await _git("pull", "--ff-only")
    if rc != 0:
        return {"ok": False,
                "error": f"git pull failed: {pull_err or pull_out or '(no message)'}"}

    # Pick up new HEAD for the response.
    _, new_head, _ = await _git("rev-parse", "HEAD")

    # Best-effort dependency refresh. Failing here is non-fatal — the
    # code is updated, the user can rerun `uv sync` manually.
    sync_status = "skipped (uv not on PATH)"
    if shutil.which("uv"):
        proc = await asyncio.create_subprocess_exec(
            "uv", "sync",
            cwd=str(_PROJECT_DIR),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=_clean_env(),
        )
        out, err_bytes = await proc.communicate()
        if proc.returncode == 0:
            sync_status = "ok"
        else:
            tail = err_bytes.decode(errors="ignore")[-400:]
            sync_status = f"failed: {tail}"

    return {
        "ok": True, "updated": True,
        "new_head": new_head[:7],
        "pull_output_tail": pull_out[-300:],
        "uv_sync": sync_status,
        "message": (
            "Updated. Type `exit` and relaunch (`uv run python ./main.py`) "
            "to load the new code — Python has the old modules cached in "
            "this process."
        ),
    }
